# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: 
title: Pablo Villalba Galiano
email: 
author: Pedro Gomez
description: > # "Write an awesome description for your new site here. 
  Designer.
copyright: 'Copyright &copy; 2021 Pedro Gomez. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: LinkedIn
    fatitle: linkedin
    url: https://www.linkedin.com/in/pablovillalbagaliano/
  #- title: Email
    #fatitle: envelope
    #url: mailto:
